apiVersion: v2
publisher: gitpod
name: code-server
version: latest
type: Che Editor
displayName: code-server
title: Visual Studio Code - Web (code-server)
description: An open source distribution of Visual Studio Code as cloud IDE
icon: /images/default.png
category: Editor
repository: 'https://github.com/coder/code-server'
spec:  
  endpoints:
    - name: code-server
      targetPort: 3000      
      attributes:
        type: ide
        protocol: http
      public: true
  containers:
    - image: 'gitpod/openvscode-server'
      mountSources: true
      memoryLimit: 1024M
      volumes:
        - name: user-data
          mountPath: /home/coder/.local/share/code-server
      name: code-server
      ports:
        - exposedPort: 3000
  initContainers: []
