apiVersion: v2
publisher: demyx
name: code-server
version: latest
type: Che Editor
displayName: code-server
title: Visual Studio Code - Web (code-server)
description: An open source distribution of Visual Studio Code as cloud IDE
icon: /images/default.png
category: Editor
repository: 'https://github.com/demyxsh/code-server'
spec:  
  endpoints:
    - name: code-server
      targetPort: 8080      
      attributes:
        type: ide
        protocol: http
      public: true
  containers:
    - image: 'demyx/docker-socket-proxy'
      mountSources: true
      memoryLimit: 1024M
      volumes:
        - name: user-data
          mountPath: /demyx
      name: code-server
      ports:
        - exposedPort: 8080
  initContainers: []
