apiVersion: v2
publisher: cdr
name: code-server
version: latest
type: Che Editor
displayName: code-server
title: Visual Studio Code - Web (code-server)
description: An open source distribution of Visual Studio Code as cloud IDE
icon: /images/default.png
category: Editor
repository: 'https://github.com/cdr/code-server'
spec:  
  endpoints:
    - name: code-server
      targetPort: 8080      
      attributes:
        type: ide
        protocol: http
      public: true
  containers:
    - image: 'codercom/code-server:4.2.0'
      mountSources: true
      memoryLimit: 4096M
      volumes:
        - name: user-data
          mountPath: /home
      name: code-server
      env:
        - value: '1234'
          name: PASSWORD
      ports:
        - exposedPort: 8080
