apiVersion: v2                                                   
publisher: valeo                                                
name: vscoretoolingextension                                             
version: 0.0.1  
type: VSCode Extension
displayName:                                                     
title:                                                           
description:                                                     
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg     
repository:                                                     
category:                                                       
spec:
  containers:                                                   
    - image:                                                    
      memoryLimit:                                              
      memoryRequest:                                            
      cpuLimit:                                                 
      cpuRequest:                                               
  extensions:                                                   
          - https://github.com/mariamiawad/VcoreExtension/blob/main/vscoretoolingextension-0.0.1.vsix
